from collections import namedtuple

Planettag = namedtuple('Planettag', ('name', 'descriptives', 'enemy', 'friend', 'complications', 'things', 'places'))

PlanetTagTable = {1: Planettag('Abandoned Colony', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  2: Planettag('Alien Ruins', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  3: Planettag('Altered Humanity', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  4: Planettag('Anarchy', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  5: Planettag('Anthropomorphs', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  6: Planettag('Area 51', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  7: Planettag('Badlands World', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  8: Planettag('Battleground', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  9: Planettag('Beastmasters', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  10: Planettag('Bubble Cities', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  11: Planettag('Cheap Life', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  12: Planettag('Civil War', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  13: Planettag('Cold War', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  14: Planettag('Colonized Population', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  15: Planettag('Cultural Power', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  16: Planettag('Cybercommunists', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  17: Planettag('Cyborgs', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  18: Planettag('Cyclical Doom', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  19: Planettag('Desert World', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  20: Planettag('Doomed World', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  21: Planettag('Dying Race', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  22: Planettag('Eugenic Cult', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  23: Planettag('Exchange Consulate', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  24: Planettag('Fallen Hegemon', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  25: Planettag('Feral World', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  26: Planettag('Flying Cities', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  27: Planettag('Forbidden Tech', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  28: Planettag('Former Warriors', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  29: Planettag('Freak Geology', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  30: Planettag('Freak Weather', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  31: Planettag('Friendly Foe', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  32: Planettag('Gold Rush', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  33: Planettag('Great Work', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  34: Planettag('Hatred', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  35: Planettag('Heavy Industry', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  36: Planettag('Heavy Mining', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  37: Planettag('Hivemind', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  38: Planettag('Holy War', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  39: Planettag('Hostile Biosphere', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  40: Planettag('Hostile Space', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  41: Planettag('Immortals', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  42: Planettag('Local Specialty', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  43: Planettag('Local Tech', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  44: Planettag('Major Spaceyard', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  45: Planettag('Mandarinate', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  46: Planettag('Mandate Base', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  47: Planettag('Maneaters', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  48: Planettag('Megacorps', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  49: Planettag('Mercenaries', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  50: Planettag('Minimal Contact', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  51: Planettag('Misandry/Misogyny', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  52: Planettag('Night World', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  53: Planettag('Nomads', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  54: Planettag('Oceanic World', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  55: Planettag('Out of Contact', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  56: Planettag('Outpost World', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  57: Planettag('Perimeter Agency', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  58: Planettag('Pilgrimage Site', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  59: Planettag('Pleasure World', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  60: Planettag('Police State', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  61: Planettag('Post-Scarcity', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  62: Planettag('Preceptor Archive', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  63: Planettag('Pretech Cultists', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  64: Planettag('Primitive Aliens', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  65: Planettag('Prison Planet', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  66: Planettag('Psionics Academy', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  67: Planettag('Psionics Fear', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  68: Planettag('Psionics Worship', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  69: Planettag('Quarantined World', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  70: Planettag('Radioactive World', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  71: Planettag('Refugees', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  72: Planettag('Regional Hegemon', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  73: Planettag('Restrictive Laws', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  74: Planettag('Revanchists', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  75: Planettag('Revolutionaries', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  76: Planettag('Rigid Culture', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  77: Planettag('Rising Hegemon', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  78: Planettag('Ritual Combat', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  79: Planettag('Robots', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  80: Planettag('Seagoing Cities', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  81: Planettag('Sealed Menace', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  82: Planettag('Secret Masters', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  83: Planettag('Sectarians', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  84: Planettag('Seismic Instability', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  85: Planettag('Shackled World', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  86: Planettag('Societal Despair', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  87: Planettag('Sole Supplier', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  88: Planettag('Taboo Treasure', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  89: Planettag('Terraform Failure', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  90: Planettag('Theocracy', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  91: Planettag('Tomb World', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  92: Planettag('Trade Hub', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  93: Planettag('Tyranny', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  94: Planettag('Unbraked AI', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  95: Planettag('Urbanized Surface', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  96: Planettag('Utopia', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  97: Planettag('Warlords', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  98: Planettag('Xenophiles', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  99: Planettag('Xenophobes', 'Descriptive', 'E', 'F', 'C', 'T', 'P'),
                  100: Planettag('Zombies', 'Descriptive', 'E', 'F', 'C', 'T', 'P')}